<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>realsense_camera_info_override</name>
  <version>0.1.0</version>
  <description>Override RealSense CameraInfo topics with calibration YAML data.</description>
  <maintainer email="duarte.cruz@isr.uc.pt">Duarte Cruz</maintainer>
  <license>ISR</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
