name: bunker_network_bridge
from_domain: 0 # Internal RouDi domain
to_domain: 133  # External multi-robot domain

topics:
  /imu/data:
    type: sensor_msgs/msg/Imu
    remap: /bunker/imu/data

  /hesai/points_filtered:
    type: sensor_msgs/msg/PointCloud2
    remap: /bunker/hesai/points_filtered

  /initial_map_filtered:
    type: sensor_msgs/msg/PointCloud2
    remap: /bunker/initial_map
    qos:
      reliability: reliable
      durability: volatile
      history: keep_last
      depth: 10

  /oak/rgb/image_raw/compressed:
    type: sensor_msgs/msg/CompressedImage
    remap: /bunker/oak/rgb/image_raw/compressed
    qos:
      reliability: reliable
      durability: volatile
      history: keep_last
      depth: 1

  /oak/rgb/camera_info:
    type: sensor_msgs/msg/CameraInfo
    remap: /bunker/oak/rgb/camera_info
    qos:
      reliability: reliable
      durability: volatile
      history: keep_last
      depth: 1

  /tf_static:
    type: tf2_msgs/msg/TFMessage
    remap: /tf_static

  /tf:
    type: tf2_msgs/msg/TFMessage
    remap: /tf

  /robot_description:
    type: std_msgs/msg/String
    remap: /bunker/robot_description

  /occupancy_map_local:
    type: nav_msgs/msg/OccupancyGrid
    remap: /bunker/occupancy_map_local

  /global_costmap/costmap:
    type: nav_msgs/msg/OccupancyGrid
    remap: /bunker/global_costmap/costmap
  
  /optimal_trajectory:
    type: nav_msgs/msg/Path
    remap: /bunker/optimal_trajectory

  /global_path:
    type: nav_msgs/msg/Path
    remap: /bunker/global_path
  
  /bunker/goal_pose:
    type: geometry_msgs/msg/PoseStamped
    remap: /goal_pose
    from_domain: 133
    to_domain: 0

  /bunker/prm_goal:
    type: geometry_msgs/msg/PoseStamped
    remap: /prm_goal
    from_domain: 133
    to_domain: 0
  

  # Reverse direction: Allow external /robot_1/cmd_vel -> internal /cmd_vel
  # /bunker/imu/data:
  #   type: sensor_msgs/msg/Imu
  #   from_domain: 133
  #   to_domain: 0